"""add_regulatory_fields_to_companies

Revision ID: c90500cb0263
Revises: 80c547d742c5
Create Date: 2026-04-27 08:43:45.996982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90500cb0263'
down_revision = '80c547d742c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reg_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reg_tax_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reg_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reg_document_path', sa.String(length=512), nullable=True))
        # credit_balance e cost_per_minute NÃO devem ser removidas — existem no banco (migration d9e5f4a1b832)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('reg_document_path')
        batch_op.drop_column('reg_address')
        batch_op.drop_column('reg_tax_id')
        batch_op.drop_column('reg_name')
        batch_op.drop_column('reg_type')

    # ### end Alembic commands ###
